### ISSUE TITLE
Methods to insert/remove rows/columns?

### ISSUE THREAD

**Issue by Boscop** [HarrisonMc555/array2d#4]
Thanks for this crate, it seems to be the only crate that provides a 2-dimensional API over Vec.
But I couldn't find any methods to insert/remove rows/columns.
It would be great if you could add them :)

(`insert` & `remove` would already be great. After that it would also make sense to have `append` and being able to `extend` rows/columns with an iter of Vecs.)

**Comment by HarrisonMc555** [comment]
Glad you found this helpful!

Originally I imagined this as a "fixed size" two-dimensional array. This was actually why I chose the name `Array2D` instead of `Vec2D`.

However, after seeing your comment and thinking about it for a while, I'm not sure if there's a huge disadvantage to adding the ability to resize the array. It will require shifting around all of the elements, but that's what happens when you remove a value from a `Vec` 🤷 

I work on this in my free time so don't expect it to show up soon but I'll try to give this a go! (unless you wanted to work on it, in which case, be my guest)

Thanks for the ideas!

**Comment by Boscop** [comment]
Thanks! I think it makes sense to support resizing because this seems to be the only crate that provides a 2-dimensional API over Vec and it's only really useful (in many use cases) when it's resizable..

**Comment by good-praxis** [comment]
I've been thinking about this for a while -- won't it often time be more efficient (depending on the size of the vec) to allocate a new vec instead of inserting it into the existing one? Inserting should work wonderfully for smaller Array2Ds, but it is a huge operation for bigger vectors, right?

So I guess we might want to think about offering both apis?

**Comment by HarrisonMc555** [comment]
After some consideration (and not coming back to this for over two years 😮 ) I've decided to retain the original goal of having this be a fixed-size array implementation. I do not anticipate adding support for insertion, deletion, or anything like that.

If you need some more capabilities, the excellent [`toodee`](https://crates.io/crates/toodee/) library is a much more feature-rich library. The `array2d` aims to be a somewhat minimal and simple representation of a 2D array.
