### ISSUE TITLE
Getting all four neighbours

### ISSUE THREAD

**Issue by alper** [HarrisonMc555/array2d#8]
I'm trying to use `get()` to get all four neighbours of a cell and it should check the bounds, but `usize` won't allow me to enter something smaller than 0 which defeats the purpose of the bounds check.

Something like this:
`a.get(i-1, j)` where i is 0.

**Comment by HarrisonMc555** [comment]
I thought about this for a while and considered using `isize` instead of `usize`. However, I wanted to match as closely as possible the behavior of regular Rust arrays and `Vec`s. I don't think I'm willing at this point to change to using `isize` instead. One possibility could be to have "isize" versions of all of the normal operations, but that seems like it would be making it much more complicated for relatively little gain.

I do sympathize, though, that this makes many algorithms more complicated. The best advice I have is to use [`usize::checked_sub`](https://doc.rust-lang.org/std/primitive.usize.html#method.checked_sub).
